"""empty message

Revision ID: 9a8d8d14b4db
Revises: 9fd790cd4249
Create Date: 2020-03-08 01:24:28.246749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8d8d14b4db'
down_revision = '9fd790cd4249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kana', sa.String(length=128), nullable=False),
    sa.Column('card_type', sa.String(length=8), nullable=False),
    sa.Column('card_attr', sa.String(length=16), nullable=True),
    sa.Column('type_', sa.String(length=16), nullable=True),
    sa.Column('has_effect', sa.Boolean(), nullable=True),
    sa.Column('is_pendulum', sa.Boolean(), nullable=True),
    sa.Column('is_fusion', sa.Boolean(), nullable=True),
    sa.Column('is_ritual', sa.Boolean(), nullable=True),
    sa.Column('is_synchro', sa.Boolean(), nullable=True),
    sa.Column('is_xyz', sa.Boolean(), nullable=True),
    sa.Column('is_link', sa.Boolean(), nullable=True),
    sa.Column('is_tuner', sa.Boolean(), nullable=True),
    sa.Column('is_toon', sa.Boolean(), nullable=True),
    sa.Column('is_union', sa.Boolean(), nullable=True),
    sa.Column('is_spirit', sa.Boolean(), nullable=True),
    sa.Column('is_gemini', sa.Boolean(), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('rank', sa.String(length=2), nullable=True),
    sa.Column('link_arrows', sa.String(length=128), nullable=True),
    sa.Column('attack', sa.String(length=5), nullable=True),
    sa.Column('defense', sa.String(length=5), nullable=True),
    sa.Column('link', sa.String(length=2), nullable=True),
    sa.Column('is_normal_spell', sa.Boolean(), nullable=True),
    sa.Column('is_continuous_spell', sa.Boolean(), nullable=True),
    sa.Column('is_field_spell', sa.Boolean(), nullable=True),
    sa.Column('is_quick_play_spell', sa.Boolean(), nullable=True),
    sa.Column('is_equip_spell', sa.Boolean(), nullable=True),
    sa.Column('is_ritual_spell', sa.Boolean(), nullable=True),
    sa.Column('is_normal_trap', sa.Boolean(), nullable=True),
    sa.Column('is_continuous_trap', sa.Boolean(), nullable=True),
    sa.Column('is_counter_trap', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('card_text', sa.String(length=512), nullable=True),
    sa.Column('pendulum_text', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['card_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_text')
    # ### end Alembic commands ###
