"""empty message

Revision ID: 9fd790cd4249
Revises: 5cae7229b8ce
Create Date: 2020-03-07 02:57:46.052077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd790cd4249'
down_revision = '5cae7229b8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_infos', sa.Column('card_no', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_infos', 'card_no')
    # ### end Alembic commands ###
