"""empty message

Revision ID: a005c591b891
Revises: 9a8d8d14b4db
Create Date: 2020-03-08 20:49:06.007648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a005c591b891'
down_revision = '9a8d8d14b4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_text', sa.Column('is_flip', sa.Boolean(), nullable=True))
    op.add_column('card_text', sa.Column('pendulum_scale', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_text', 'pendulum_scale')
    op.drop_column('card_text', 'is_flip')
    # ### end Alembic commands ###
